### ISSUE TITLE
KeyError: 'SKIMMER_FLOW'

### ISSUE THREAD

**Issue by thenoid** [dwradcliffe/home-assistant-waterguru#10]
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
homeassistant  |     await self._async_refresh(log_failures=True, scheduled=True)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
homeassistant  |     self.async_update_listeners()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
homeassistant  |     update_callback()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _handle_coordinator_update
homeassistant  |     self.async_write_ha_state()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
homeassistant  |     self._async_write_ha_state()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
homeassistant  |     self.__async_calculate_state()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
homeassistant  |     state = self._stringify_state(available)
homeassistant  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
homeassistant  |     if (state := self.state) is None:
homeassistant  |                  ^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 542, in state
homeassistant  |     value = self.native_value
homeassistant  |             ^^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/waterguru/sensor.py", line 240, in native_value
homeassistant  |     m = self.coordinator.data[self._id].measurements[self._waterguru_key]
homeassistant  |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
homeassistant  | KeyError: 'SKIMMER_FLOW'

**Comment by dwradcliffe** [comment]
This one should be fixed in the latest version. Let me know if you still have problems.
