### ISSUE TITLE
Error loading if cassette counter is reset

### ISSUE THREAD

**Issue by Scope666** [dwradcliffe/home-assistant-waterguru#6]
If you click "Replace Cassette" in the app, the **timeLeftText** variable won't be available until another test is performed, and the integration won't load.  Perhaps a conditional check can be put in to continue loading if it isn't available:

```
2024-05-29 10:13:18.261 INFO (SyncWorker_1) [custom_components.waterguru.waterguru] Fetching data from WaterGuru API...
2024-05-29 10:13:26.302 ERROR (MainThread) [custom_components.waterguru] Unexpected error fetching waterguru data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waterguru/__init__.py", line 39, in _update_method
    return await hass.async_add_executor_job(waterguru.get)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waterguru/waterguru.py", line 77, in get
    return {waterBodyData['waterBodyId']: WaterGuruDevice(waterBodyData) for waterBodyData in data['waterBodies']}
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waterguru/waterguru.py", line 98, in __init__
    if "days" in r['timeLeftText']:
                 ~^^^^^^^^^^^^^^^^
KeyError: 'timeLeftText'
```

This is what the API returns when the cassette is at 100%   (button has been pushed in app)

![image](https://github.com/dwradcliffe/home-assistant-waterguru/assets/31927547/aed89c1c-363a-4e34-bed0-2c450acd62aa)

![Screenshot_1](https://github.com/dwradcliffe/home-assistant-waterguru/assets/31927547/dc0d70e0-eac6-41f5-9465-b96784b6e71d)

**Comment by WorldOfMaze** [comment]
I noticed that missing data for a while and wondered why.

What i am seeing in HA is the same number displayed in the app without the units.  When I first replaced the cartridge the number was `2` and the unit was `months`.  The next day it was `8` and `weeks`.

If the units -- `days`, `weeks`, or `months` is not available in the API, perhaps you could include `pctLeft` as an attribute.  I know that when I load a new cartridge it is good for 60 days.  With `pctLeft`, I could calculate the correct number of days.

Anything you can do to resolve this will be greatly appreciated.

Thanks for your help.

**Comment by dwradcliffe** [comment]
Thanks for the report. This is fixed in the latest code. Note that you may have to reload the integration to get the `Cassette Days Remaining` sensor to work after the first test, but at least it won't fail to setup now.
