### ISSUE TITLE
Missing PH Sensor

### ISSUE THREAD

**Issue by madasus** [dwradcliffe/home-assistant-waterguru#7]
For the past few days my installation has been telling me that the PH entity is no longer provided.  Anyone else seeing this? did they rename something on the API?

![image](https://github.com/user-attachments/assets/46eb8055-d57f-40ba-b72e-a625a4a6bb3e)

**Comment by dwradcliffe** [comment]
I just checked and mine worked ok this morning. Try restarting HA?

**Comment by madasus** [comment]
Yeah I restarted HA and the integration.

I am in a PH alert state right now - pH low.

Maybe it breaks where there is a PH Alert?

**Comment by dwradcliffe** [comment]
Did you happen to replace your cassette recently? If HA restarts right after your cassette is replaced this might happen.

If this happens again you can press the debug button on this integration and send me the debug output it gives you.

**Comment by madasus** [comment]
No - it was replaced a week or so ago - i've had 3 or 4 readings from this cassette already so it should be fine.

[config_entry-waterguru-e3cc3dc5130af6ac741899bb46ef5bbf.json](https://github.com/user-attachments/files/16203339/config_entry-waterguru-e3cc3dc5130af6ac741899bb46ef5bbf.json)

Is this the correct file?

**Comment by WorldOfMaze** [comment]
@madasus Mine is working fine.  I am using the original -- pH + Chlorine levels only -- WaterGuru.

**Comment by madasus** [comment]
Confirmed - I cleared the PH error today (by fixing the water in the pool!) and now the PH numbers are showing back up in HA.

Looks like the integration maybe isn't handling PH related errors correctly?

**Comment by dwradcliffe** [comment]
That was the correct debug file, thank you. I looked at your data and the code and my data and I can't figure out why it wouldn't work. Were there any errors in your log?

**Comment by madasus** [comment]
It looks like there was

`024-07-13 07:12:50.184 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.waterguru_newtown_ph for domain sensor with platform waterguru
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 912, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1362, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1072, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waterguru/sensor.py", line 226, in extra_state_attributes
    a[WaterGuruEntityAttributes.ADVICE] = m.get("alerts")[0].get("advice").get("action").get("summary")
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2024-07-13 07:12:50.199 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.waterguru_newtown_ph_alert for domain sensor with platform waterguru
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 912, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1362, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1072, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waterguru/sensor.py", line 226, in extra_state_attributes
    a[WaterGuruEntityAttributes.ADVICE] = m.get("alerts")[0].get("advice").get("action").get("summary")
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by dwradcliffe** [comment]
Ah! I see the problem now. I'll work on a fix. It seems that because you didn't set the type of acid you use, it doesn't give you any advice and the API result is different. The code should handle this.

**Comment by dwradcliffe** [comment]
I've pushed a fix for this.
